name: islami_app
description: "Islam App."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  adhan_dart: ^1.1.2
  animate_do: ^3.3.4
  audioplayers: ^6.1.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_compass: ^0.8.1
  flutter_islamic_icons: ^1.0.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.14
  geolocator: ^13.0.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  loading_animation_widget: ^1.3.0
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
